dist: xenial

language: go

go:
  - 1.11.x
  - 1.12.x

# Only clone the most recent commit.
git:
  depth: 1

install:
  - travis_retry travis-scripts/run-containers.sh

notifications:
  email: false

before_script:
  - go get -u github.com/parnurzeal/gorequest
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega/...

script:
  - ginkgo -v -r
  - go build
