dist: xenial

services:
  - docker

env:
  - CODECOV_TOKEN="0c5360a0-6fa7-4949-80f3-bb3ceb8d9d3f"

language: go

go:
  - 1.11.x
  - 1.12.x

git:
  depth: 1

before_install:
  - docker run -d -p 2525:2525 -p 6789:6789 expert360/mountebank start --mock

notifications:
  email: false

before_script:
  - go get -u github.com/parnurzeal/gorequest
  - go get -u github.com/onsi/ginkgo/ginkgo
  - go get -u github.com/onsi/gomega/...
  - go get github.com/modocache/gover

script:
  - ginkgo -v -r --cover
  - gover
  - go build

after_success:
  - mv gover.coverprofile coverage.txt
  - bash <(curl -s https://codecov.io/bash)
